name: Diabetes Retraining Pipeline with Data Drift Detection_adry

on:
  push:
    
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4